-- Generated by Oracle SQL Developer Data Modeler 23.1.0.087.0806
--   at:        2024-04-21 19:30:13 YEKT
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g



-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE artist (
    id   INTEGER PRIMARY KEY UNIQUE,
    name text
);

CREATE TABLE genre (
    id   INTEGER PRIMARY KEY NOT NULL UNIQUE,
    name text
);

CREATE TABLE label (
    id   INTEGER PRIMARY KEY NOT NULL UNIQUE,
    name text
);

CREATE TABLE album (
    id     INTEGER PRIMARY KEY NOT NULL UNIQUE,
    name   text,
    year   DATE,
    single CHAR(1),
    label  INTEGER NOT NULL,
    artist INTEGER NOT NULL,
    genre  INTEGER NOT NULL,
    FOREIGN KEY (artist) REFERENCES artist(id),
    FOREIGN KEY (genre) REFERENCES genre(id),
    FOREIGN KEY (label) REFERENCES label(id)
);

CREATE TABLE track (
    id        INTEGER PRIMARY KEY NOT NULL UNIQUE,
    name      text,
    album_num INTEGER,
    year      DATE,
    album     INTEGER NOT NULL,
    artist    INTEGER,
    FOREIGN KEY (album) REFERENCES album(id),
    FOREIGN KEY (artist) REFERENCES artist(id)
);

ALTER TABLE track DISABLE TRIGGER track_artist_fkey;
ALTER TABLE track DISABLE TRIGGER track_album_fkey;


-- Oracle SQL Developer Data Modeler Summary Report:
--
-- CREATE TABLE                             5
-- CREATE INDEX                             0
-- ALTER TABLE                             15
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
--
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
--
-- REDACTION POLICY                         0
--
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
--
-- ERRORS                                   0
-- WARNINGS                                 0
